services:
  - type: static
    name: classview-plickers
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=300
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
